#include "afq_caffe_cnn.h"
#include "mobilecv.h"

static long getfilesize(FILE*stream)
{
	long curpos, length;
	curpos = ftell(stream);
	fseek(stream, 0L, SEEK_END);
	length = ftell(stream);
	fseek(stream, curpos, SEEK_SET);
	return length;
}

const float binarynet_model_info_mnist[] =
{
	13,
	CAFFECNN_LAYER_CODE_DATA, 1, 28, 28, 0.00390625,
	CAFFECNN_LAYER_CODE_FC, 4096, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,
	CAFFECNN_LAYER_CODE_FC, 4096, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,
	CAFFECNN_LAYER_CODE_FC, 4096, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,
	CAFFECNN_LAYER_CODE_FC, 10, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_CATEGORY
};

const float binarynet_model_info_cifar10[] =
{
	31,

	CAFFECNN_LAYER_CODE_DATA, 3, 32, 32, 0.00390625,

	CAFFECNN_LAYER_CODE_CONV, 128, 3, 3, 1, 1, 1, 1, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,
	CAFFECNN_LAYER_CODE_CONV, 128, 3, 3, 1, 1, 1, 1, 1,
	CAFFECNN_LAYER_CODE_POOLING, 2, 2, 0, 0, 2, 2, CAFFECNN_POOLING_CODE_MAX,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,

	CAFFECNN_LAYER_CODE_CONV, 256, 3, 3, 1, 1, 1, 1, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,
	CAFFECNN_LAYER_CODE_CONV, 256, 3, 3, 1, 1, 1, 1, 1,
	CAFFECNN_LAYER_CODE_POOLING, 2, 2, 0, 0, 2, 2, CAFFECNN_POOLING_CODE_MAX,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,

	CAFFECNN_LAYER_CODE_CONV, 512, 3, 3, 1, 1, 1, 1, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,
	CAFFECNN_LAYER_CODE_CONV, 512, 3, 3, 1, 1, 1, 1, 1,
	CAFFECNN_LAYER_CODE_POOLING, 2, 2, 0, 0, 2, 2, CAFFECNN_POOLING_CODE_MAX,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,

	CAFFECNN_LAYER_CODE_FC, 1024, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,
	CAFFECNN_LAYER_CODE_FC, 1024, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_BINARY,
	CAFFECNN_LAYER_CODE_FC, 10, 1,
	CAFFECNN_LAYER_CODE_BATCHNORM,
	CAFFECNN_LAYER_CODE_CATEGORY
};


int main()
{
	FILE* fd_CNNModel = fopen("cifar/cifar10_2.bin", "rb");
	if (!fd_CNNModel)
	{
		printf("fail to open model file\n");
		system("pause");
		return;
	}
	lsize = getfilesize(fd_CNNModel);
	pCNNModel = (float*)malloc(lsize);
	if (!pCNNModel)
	{
		printf("no memory to load model file\n");
		system("pause");
		return;
	}
	fread(pCNNModel, 1, lsize, fd_CNNModel);
	fclose(fd_CNNModel);
}